Adds an alias to make debugging easier!
tinkerbell/hook pull request #82
Opened 2021-09-08 14:17 UTC by thebsdbox

## Description

This adds an `alias` to hook.yaml and hook_debug.yaml, that makes debugging much more simple.
 
## Why is this needed

Remembering the `ctr` command is nigh on impossible. 

Fixes: #

The pain of trying to remember the `ctr` flags :-)

## How Has This Been Tested?

## How are existing users impacted? What migration steps/scripts do we need?

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

2021-09-08 14:18 UTC, thebsdbox commented
Fixes #81

2021-09-09 00:33 UTC, tstromberg requested changes

2021-09-09 00:33 UTC, tstromberg commented on hook.yaml
> +      alias l='ls -lF'
These first two aliases feel a bit like scope creep to me. Would it be OK to remove them?

2021-09-09 00:33 UTC, tstromberg commented on hook_debug.yaml
> +  - name: dhcpcd
Please split this unrelated change into another PR.

2021-10-05 15:27 UTC, splaspood approved these changes

2021-10-05 15:30 UTC, merged